### ISSUE TITLE
Issue with sections 2+

### ISSUE THREAD

**Issue by ActionJONA** [at-tools/moodle-block_massaction#11]
Hi, 
The mass actions check boxes appear when viewing all sections on one page, but when inside a section (using the "Show one section per page" Course Layout), only section 0 & 1 display the checkboxes, not the rest.

This is using:
Moodle 3.1.2+ (Build: 20160915)
Mass action block  (Build: 2016052401)

**Comment by rrusso** [comment]
If you're using the latest master, this bug is fixed with the js/module_selector.js from 3f96c2814be17859a3e8eaf0cd046d9410d67c91. Can the guys at UMN get on this?

**Comment by ActionJONA** [comment]
We're using v1.2.4, if it was fixed in v1.2.3, then it's broken again!?

**Comment by rrusso** [comment]
That is correct. It was fixed and then someone overwrote the correct commit. I'm not at UMN, so cannot fix the issue. It's simply a matter of using the js/module_selector.js from v1.2.3 in your 1.2.4 instance. I'm about to deploy this to our production environment this Sunday.

**Comment by ActionJONA** [comment]
I see, thanks for this info. I will get this updated on our v1.2.4

**Comment by ActionJONA** [comment]
Just to let you know, simply replacing the v1.2.4 version of js/module_selector.js with the 1.2.3 version doesn't work. It just gets stuck on the "You must enable Javascript to use this block." message.

**Comment by rrusso** [comment]
Sorry, you are correct. I ended up merging 1.2.3 and 1.2.4. I'm sure they'll get to it.

**Comment by ActionJONA** [comment]
Ahh ok, well if you're feeling particularly generous, I'd be open to seeing your working version of the corrected files (I'm very aware that this will not be an official version)

**Comment by cdsmith-umn** [comment]
I'm working to address this now. I apologize for the delay and inconvenience.

**Comment by cdsmith-umn** [comment]
I have fixed this and will be pushing a new version to Github and the Moodle Plugins directory in the near future (probably no later than tomorrow, but possibly as early as today).
