### ISSUE TITLE
"Coding Error Detected" on delete

### ISSUE THREAD

**Issue by slartimitvar** [at-tools/moodle-block_massaction#15]
Hi

I'm testing v2.0.0 of block_massaction on Moodle 3.1.2+ (Build: 20160915) and the delete action generates the following to errors at the bottom of the "confirm mass deletion" page.
Clicking the Delete button twice achieves the desired outcome.
Using Clean theme.

Coding error detected, it must be fixed by a programmer: You cannot redirect after the entire page has been generated
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 3 and state 3 was requested.

**Comment by cdsmith-umn** [comment]
@slartimitvar I'll have a look at that as soon as I'm able. I did notice when deleting that there is malformed HTML (there are two closing tags that are missing), but I haven't had time to dig into that, yet either.

**Comment by jedosaurus** [comment]
I think that I happened on this issue too. We are running Moodle 3.0.7 (Build: 20161114) and Mass actions block v.2016111700
![mdl mass-actions error](https://cloud.githubusercontent.com/assets/5129382/21441013/92afe72e-c85b-11e6-9acf-1184d363d732.png)

**Comment by cdsmith-umn** [comment]
@jedosaurus Thanks for the report on this. I'm hoping to have time this month to start work on this. It might be pushed to February. I'm going to discuss with my analysts the work-flow for deleting items using the Mass Actions block and see if there are any improvements that can be made to it.

**Comment by ctam** [comment]
Hi, just want to note that we're encountering this issue in Moodle 2.7 as well.  Thanks for taking the time addressing this.

**Comment by cdsmith-umn** [comment]
This has been fixed in all versions from 2.4 through 3.2.
