### ISSUE TITLE
Bugs with checkbox, selection and dropdown

### ISSUE THREAD

**Issue by doiphode** [at-tools/moodle-block_massaction#18]
- Bug in the code while defining array
- The plugin had issue with js due to undefined variable. It affected the populating of the select box dropdown.
- Only the last item was selected after clicking on select all for a section

Fixes are on 'doiphode' branch on my repo
https://github.com/doiphode/moodle-block_massaction

Updated Readme

**Comment by cdsmith-umn** [comment]
Not enough information to reproduce the problem.
