### ISSUE TITLE
Required Moodle version set incorrectly?

### ISSUE THREAD

**Issue by NMCPaul** [at-tools/moodle-block_massaction#19]
In both the `master` and `moodle-33-master` branch, it shows that the required Moodle version is:
```
$plugin->requires = 20171051500;
```
I'm at the latest Moodle version (3.3.2+) and I'm showing that the version is:
```
$version  = 2017051502.02;
```
I think there might be a typo in your `version.php`.  An extra `1` after the `2017` maybe?

**Comment by cdsmith-umn** [comment]
@NMCPaul That is a typo. I'll get that fixed right away!

**Comment by cdsmith-umn** [comment]
@NMCPaul v5.0.1 is up with the corrected Moodle version. I apologize for the inconvenience!

**Comment by cdsmith-umn** [comment]
I should add that you can get it either on Github or on the Moodle plugins directory.

**Comment by NMCPaul** [comment]
Excellent.  Thanks for the fast turnaround!

**Comment by cdsmith-umn** [comment]
You're welcome.
