### ISSUE TITLE
Impossible to use - message jsdisabled

### ISSUE THREAD

**Issue by foxlapinou** [at-tools/moodle-block_massaction#20]
I use Moodle 3.3.2, and i've just updated the Mass Action bloc to the latest version (5.0.0). Since then, when i try to use it, i see the message "You must enable Javascript to use this block." (jsdisabled string).
Everything was fine with the previous version.

**Comment by cdsmith-umn** [comment]
@foxlapinou Looking into this right now.

**Comment by cdsmith-umn** [comment]
@foxlapinou v5.0.1 is up both here on Github and on the Moodle plugins directory. This fixes the problem that you were having. My apologies for the inconvenience!

**Comment by foxlapinou** [comment]
Thanks you very much for the very quick update. It works OK with the new version.

**Comment by cdsmith-umn** [comment]
Glad to hear it!

**Comment by foxlapinou** [comment]
It seems that users using Firefox 45.9.0.0 still have the same problem :-(
And, unfortunatly, our university his "blockink" Firefox to this version for this academic year.
Do you think you can do something to make this bloc compatible with older Firefox versions?

**Comment by cdsmith-umn** [comment]
@foxlapinou I'm going to simply remove the check for whether javascript is enabled altogether. It's been a problem before and the help text in the block clearly informs the user that javascript is required to use the block. I apologize for the inconvenience.

Also, I'm restoring the deletion confirmation page. I've had requests for that and it seems that Firefox does not always display the javascript confirmation dialog box. So, that'll be making a return at the same time.

I expect to have the new version up later today (26 September).

**Comment by cdsmith-umn** [comment]
@foxlapinou In fact, after this version, the next version will include a configuration page. So, I'll re-add the check for whether javascript is enabled at that time and make it a configurable setting. That way the people who like having that check can have it and the people who either don't like or find it's causing trouble for some users can disable it.

**Comment by foxlapinou** [comment]
@cdsmith-umn Thanks for the explanation. I understand that different people want different things, and i think that the configuration page will be a good thing.
When the new version will be available, i'll test it to confirm it's OK for my case...

**Comment by cdsmith-umn** [comment]
@foxlapinou I will have the new version up either tomorrow or by Thursday at the latest. I apologize for the delay and the inconvenience. I've coded the configuration page and tested that. I'm having the code reviewed right now. Tests in Travis-CI all pass for the build. Thank you for your patience!

**Comment by foxlapinou** [comment]
@cdsmith-umn Thanks for your quick work on this !
Waiting one ore two days is not a problem ; we're not talking about weeks or months ;-)

**Comment by cdsmith-umn** [comment]
@foxlapinou The new version is up: v5.0.2. You can get it either from the plugins directory or directly from https://github.com/at-tools/moodle-block_massaction/archive/moodle-33-master.zip. The admin setting defaults to "off"/"disabled"/"no" because I felt that was a safer and more user-friendly setting.

**Comment by cdsmith-umn** [comment]
Also, it might be that some of your users are encountering a javascript error, which will cause the block to become unusable. If they're still having trouble, try to find out if this is the case and - if so - what is throwing the error. (Or perhaps they've disabled javascript in their browsers?) If it is something I can fix, I certainly will!

**Comment by foxlapinou** [comment]
@cdsmith-umn I've installed and tested the new version. The results:

- if javascript check is enabled, same as before (OK with latest Firefox and Chrome, jsdisabled string shown for Firefox 45.9.0.0), as expected
- if javascript check is disabled, the bloc is void for everybody (shown with nothing inside), where you expect to have everything to use it
I think you've missed something.

**Comment by foxlapinou** [comment]
In fact, the strange thing is that everything was OK with Firefox 45.9.0.0 with the previous (3.0.2) version...

**Comment by cdsmith-umn** [comment]
@foxlapinou Well, that doesn't make any sense as to why v5.0.1 wouldn't work for all your users, then. The only thing I can think of is that there is something about the change to jQuery/AMD that is causing a problem. I'm going to create a version without that javascript check for you to try out. Let's see if removing it entirely makes a difference.

**Comment by cdsmith-umn** [comment]
No, I see that there was a problem with the last build. Grrr.

**Comment by cdsmith-umn** [comment]
I'm still going to just create a version without the javascript check. I'm starting to seriously consider removing it altogether because it's been such a pain.

**Comment by cdsmith-umn** [comment]
@foxlapinou Please try this and see if the problem is finally resolved. Thank you!

https://github.com/at-tools/moodle-block_massaction/archive/moodle-33-no-javascript-check.zip

**Comment by foxlapinou** [comment]
@cdsmith-umn Thanks for the new version. I've tested it, but it's worse : it's now like the second test i've made previously (no javascript check) : it shows a "blank" (void) block for everybody (every browser i use). But no way (option) to make it work :-(
It's like if a test was made the wrong way, not displaying things when it should...

Appart that, i think that :
- javascript test can be dropped, because (relativly) recent browsers DO support javascript
- you can avoid putting (french) translation ; it's made in AMOS (i've updated it)

**Comment by cdsmith-umn** [comment]
Hmmm. I'll get this figured out. Seems strange to me, but I know there's a solution.

**Comment by cdsmith-umn** [comment]
@foxlapinou OK. Somehow the "hidden" class was still present on the div that contains the block. I had tested the changes and they'd worked, but I'd done some undoing and redoing after that and forgot to test again. I have made the change and tested again, this time without any undo/redo actions. This version should work correctly. Thank you again for your patience.

**Comment by foxlapinou** [comment]
@cdsmith-umn I've downloded and tested the new version. It's OK for recent Firefox and Chrome version :-)
But with Firefox 45.9.0.0, i first thought it was OK (because the bloc was showing), but :
- in the bloc, the 3 menus (to select section) just show the title (with NO section after)
- in the course page, the tick box don't show

So, still not usable at all with this Firefox version.

**Comment by cdsmith-umn** [comment]
There has got to be a javascript error being thrown, then. There's something happening that's causing the javascript to stop processing. I actually happen to have Firefox 45.9.0 installed on my home system (working from home today). So, I'll see if I can find out what's going on with this.

**Comment by cdsmith-umn** [comment]
@foxlapinou I found the error, corrected it, and tested the change. The block works in FF 45.9.0 for me and still works in Chrome, as well. Please confirm whether this fixes the problem for your users, as well.

**Comment by foxlapinou** [comment]
@cdsmith-umn It's easier to test with the same environment.
I've verified, and it works OK now :-)
Thanks a lot for all the quick updates. I mark as closed.

**Comment by cdsmith-umn** [comment]
You're welcome. I'll get this version up on the plugins directory today.
