### ISSUE TITLE
OneTopic format

### ISSUE THREAD

**Issue by cdsmith-umn** [at-tools/moodle-block_massaction#3]
When a course is put into OneTopic format with the Mass Actions block added (either before or after the OneTopic format is selected) and editing is turned on, the Mass Actions block will only draw the checkboxes on the page for the default tab (section 0). Additionally, the drop menus for "Select All" and "Move to Section" are not populated.

These are known issues and will not be fixed for the foreseeable future. The workaround for those users who put their courses into the OneTopic format is to change the format to one in which Mass Actions works correctly, make the changes they wish to make, then put the course back into OneTopic format.

**Comment by Syxton** [comment]
Just created a pull request that would fix this issue.  Also fixes the case where sections are non consecutive. AKA Topic 1, Topic 2, Topic 3, Orphaned section 5, Orphaned section 6 https://github.com/at-tools/moodle-block_massaction/pull/9

**Comment by cdsmith-umn** [comment]
This is being worked on and is nearly complete. I'll try to also get this fix applied to the version for Moodle 2.7 and earlier.

**Comment by cdsmith-umn** [comment]
This has been fixed in both versions of the Mass Actions block, both for Moodle 2.4 to 2.7 and Moodle 2.8 and up.
