### ISSUE TITLE
Feature request:  Duplicating items

### ISSUE THREAD

**Issue by bgoodlin01** [at-tools/moodle-block_massaction#5]
This block greatly speeds up my workflow.  Thanks!

I'd like to request an ability to duplicate items.  Simply duplicating selected items into the same section might occasionally be helpful, but what would be really helpful would be an ability to select multiple items in a given section and duplicate them into another, much like the "Move to section" dropdown, but "Duplicate to section" instead.

**Comment by Syxton** [comment]
I agree this is a much needed feature.

**Comment by Syxton** [comment]
I just created a pull request to add this feature.  https://github.com/at-tools/moodle-block_massaction/pull/8

**Comment by cdsmith-umn** [comment]
I missed these comments at the time. This has been added.
