### ISSUE TITLE
Disable block if Javascript is disabled in the browser

### ISSUE THREAD

**Issue by Kathrin84** [at-tools/moodle-block_massaction#6]
Hi,

in my tests I evaluated that Javascript has to be turned on for the block to function. 
If a user has Javascript turned off, it would be helpful for this user if the block would be disabled or invisible as he cannot use it at all.

Is that possible? What do you think? 
At least a message could be displayed that Javascript is needed.

Cheers,
Kathrin

**Comment by cdsmith-umn** [comment]
I will take a look into that, as well.

**Comment by cdsmith-umn** [comment]
@Kathrin84 

I can only check whether Javascript is enabled if Javascript is enabled. If it is disabled, then I have no client-side code I can run to alert the user that they need Javascript to use this block. I don't have a way to add a <noscript> tag to disable the use of the block, either. The best I can do is to make sure that anyone who looks up the plugin on the Plugins Directory sees that Javascript is required.

**Comment by Kathrin84** [comment]
Hi @cdsmith-umn,

in HTML it's possible to put code in the tags <noscript> (http://www.w3schools.com/tags/tag_noscript.asp) Maybe that could help?

**Comment by cdsmith-umn** [comment]
I've got this working. Sorry for the confusion.
