### ISSUE TITLE
Feature Request: add further actions to the block

### ISSUE THREAD

**Issue by Kathrin84** [at-tools/moodle-block_massaction#7]
Hi,

I really like this block and thought about extending the functionality to additional actions like setting access restrictions to items and sections. 
What do you think about it?

Cheers,
Kathrin

**Comment by cdsmith-umn** [comment]
That's certainly a possibility. I'll bring it up with my analysts and see what they think about this.

**Comment by cdsmith-umn** [comment]
@Kathrin84 I've talked it over with other members of my team and this is really out of scope for this plug-in. The particulars that you're asking to be able to set using this is really a configuration setting for each module/activity. This plug-in is focused on organizing the course main page. If an activity or module is duplicated, the resulting clone inherits whatever settings existed for the original activity or module at the time the clone was created.
